# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0zbg2sc4pd04rq2i0inhwcqwvial9ss3nxgzzz2m6v8rgra8g1ax";
    aarch64-linux = "1hrmdw3fnz0nb5bh8psmahkqksylz8rjiqrgdizq7p63bif1f0kl";
    x86_64-darwin = "0rpilissg78dn5nvgvc692w8awjnbjv5kmj11bxiflr7j23w24a6";
    aarch64-darwin = "18qc2bzzaq5i2icz0x8931np8scr6qrqbgfnck9pk2k4dsimy775";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.3/lore-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.3/lore-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.3/lore-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.3/lore-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "lore";
  version = "0.1.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./lore $out/bin/lore
  '';

  meta = {
    description = "Agent skills package manager";
    homepage = "https://github.com/pierreWagou/lore";
    license = lib.licenses.mit;
    mainProgram = "lore";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
