# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1nzxlmw4pq6sy6laph2q9n67cz5nrjldzzgr9w28c2vqlm66qglw";
    aarch64-linux = "0awy1iavck9v5ybii8vm207pvk0pdcyhbaw6hr2sxizr6dl496a6";
    x86_64-darwin = "0f5711g0fxfkq57srsn73zimmx7lky7gdfvyckd7k78gpfih0wp2";
    aarch64-darwin = "1hb9xcf7g4k5sii7vssb2vwx8c4c4z3927pb9wjv81cwlc7xn9pw";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.7/lore-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.7/lore-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.7/lore-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.7/lore-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "lore";
  version = "0.1.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./lore $out/bin/lore
  '';

  meta = {
    description = "Agent skills package manager";
    homepage = "https://github.com/pierreWagou/lore";
    license = lib.licenses.mit;
    mainProgram = "lore";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
