# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0a2y8vbdx63h1w1l20jd1a1d5p32b0q8wxryq6434mdv118f5c4i";
    aarch64-linux = "109mfx2180aal434j35rycs6g9mi0xixy00fw347c7v2h119vmq2";
    x86_64-darwin = "0xln08s3yaszg5i40xym5br913z8akvqijvvagcpiaxxi2w279zp";
    aarch64-darwin = "0fjz9qa8slbhpc55l3hhjjbfv114ln0xpnpbywiijd42a1jmd30k";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.6/lore-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/pierreWagou/lore/releases/download/v0.1.6/lore-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.6/lore-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/pierreWagou/lore/releases/download/v0.1.6/lore-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "lore";
  version = "0.1.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./lore $out/bin/lore
  '';

  meta = {
    description = "Agent skills package manager";
    homepage = "https://github.com/pierreWagou/lore";
    license = lib.licenses.mit;
    mainProgram = "lore";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
